---
name: "Spellcheck"
on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - "spellcheck.yaml"
      - "wordlist.txt"
      - ".github/workflows/spellcheck.yaml"
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - "spellcheck.yaml"
      - "wordlist.txt"
      - ".github/workflows/spellcheck.yaml"

jobs:
  spellcheck:
    name: "Spellcheck"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "rojopolis/spellcheck-github-actions@dbd2f1da869c05ad874fffeb6fe1ed50cd1a6e98" # v0.36.0
        name: "Spellcheck"
        with:
          config_path: "spellcheck.yaml"
